replicaCount: 1

image:
  repository: dimeder13/frontend

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: softserve.dimeder.pp.ua
      paths: [/]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

URL_GET: http://get-srv:8081
URL_POST: http://post-srv:8082/a