apiVersion: apps/v1
kind: Deployment
metadata:
  name: get
  labels:
    app: get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get
  template:
    metadata:
      labels:
        app: get
    spec:
      containers:
        - name: get
          image: nikitasadok/go-get-service
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
          - configMapRef:
              name: get-conf
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"