---
galaxy_info:
  author: sudipt.sharma@opstree.com
  description: OpenVpn ansible role for creating a secure tunnel to your private infra.
  company: "Opstre Solutions"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
