- job_name: frontend
  scrape_interval: 3s
  scrape_timeout: 3s
  metrics_path: /metrics
  honor_labels: true
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: 
      - __meta_kubernetes_namespace 
      - __meta_kubernetes_pod_label_app_kubernetes_io_instance
      - __meta_kubernetes_pod_container_port_name
      action: keep
      regex: default;frontend;http
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      target_label: pod
    - source_labels: [__meta_kubernetes_pod_phase]
      target_label: status


