---
apiVersion: v1
kind: Service
metadata:
  name: front-srv
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front 
